In [1]:
import sys
!{sys.executable} -m pip install --upgrade --force-reinstall "git+https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git@main"

Collecting git+https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git@main
  Cloning https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git (to revision main) to /private/var/folders/n3/wd1bprj14gjf3l0y580nx2z40000gq/T/pip-req-build-mz888mii
  Running command git clone --filter=blob:none --quiet https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git /private/var/folders/n3/wd1bprj14gjf3l0y580nx2z40000gq/T/pip-req-build-mz888mii
  Running command git checkout -b main --track origin/main
  Switched to a new branch 'main'
  branch 'main' set up to track 'origin/main'.
  Resolved https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git to commit d1592460b584a2651f10136836a9fc4d5ac6e0fd
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting httpx<1,>=0.27 (from picsure==0.1.0)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting pandas<3,>=2 (from picsure==0.1.0)
  Using cached pandas-2.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting anyio (from httpx<1,>=0.27->picsure==0.1.0)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting certifi (from httpx<1,>=0.27->picsure==0.1.0)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.27->picsure==0.1.0)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.27->picsure==0.1.0)
  Using cached idna-3.12-py3-none-any.whl.metadata (8.0 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.27->picsure==0.1.0)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting numpy>=1.23.2 (from pandas<3,>=2->picsure==0.1.0)
  Using cached numpy-2.4.4-cp311-cp311-macosx_14_0_arm64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas<3,>=2->picsure==0.1.0)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas<3,>=2->picsure==0.1.0)
  Using cached pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas<3,>=2->picsure==0.1.0)
  Using cached tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas<3,>=2->picsure==0.1.0)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting typing_extensions>=4.5 (from anyio->httpx<1,>=0.27->picsure==0.1.0)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached pandas-2.3.3-cp311-cp311-macosx_11_0_arm64.whl (10.8 MB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached numpy-2.4.4-cp311-cp311-macosx_14_0_arm64.whl (5.5 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Using cached idna-3.12-py3-none-any.whl (68 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Building wheels for collected packages: picsure
  Building wheel for picsure (pyproject.toml) ... done
  Created wheel for picsure: filename=picsure-0.1.0-py3-none-any.whl size=46836 sha256=bba804bcbae07521d5c3492412587e0bded5e0dc63c80e2e4da5bfea289b6c2a
  Stored in directory: /private/var/folders/n3/wd1bprj14gjf3l0y580nx2z40000gq/T/pip-ephem-wheel-cache-e_scqjqg/wheels/5b/5f/97/e7864a47e28aaf9d463ca212b6f2aa6fff8256e5e05bebd2e3
Successfully built picsure
Installing collected packages: pytz, tzdata, typing_extensions, six, numpy, idna, h11, certifi, python-dateutil, httpcore, anyio, pandas, httpx, picsure
  Attempting uninstall: pytz
    Found existing installation: pytz 2026.1.post1
    Uninstalling pytz-2026.1.post1:
      Successfully uninstalled pytz-2026.1.post1
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2026.1
    Uninstalling tzdata-2026.1:
      Successfully uninstalled tzdata-2026.1
  Attempting uninstall: typing_extensions━━━━━━━━━━━━━━━━━━━━━━━━━  1/14 [tzdata]
    Found existing installation: typing_extensions 4.15.0━━━━━  1/14 [tzdata]
    Uninstalling typing_extensions-4.15.0:━━━━━━━━━━━━━━━━━━━━  1/14 [tzdata]
      Successfully uninstalled typing_extensions-4.15.0━━━━━━━━━━━  2/14 [typing_extensions]
  Attempting uninstall: sixm━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/14 [typing_extensions]
    Found existing installation: six 1.17.0━━━━━━━━━━━━━━━━━━━  2/14 [typing_extensions]
    Uninstalling six-1.17.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/14 [typing_extensions]
      Successfully uninstalled six-1.17.0━━━━━━━━━━━━━━━━━━━━━━━━━  3/14 [six]xtensions]
  Attempting uninstall: numpy0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/14 [six]
    Found existing installation: numpy 2.4.4━━━━━━━━━━━━━━━━━━  3/14 [six]
    Uninstalling numpy-2.4.4:0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/14 [six]
      Successfully uninstalled numpy-2.4.4━━━━━━━━━━━━━━━━━━━━  3/14 [six]
  Attempting uninstall: idna╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/14 [numpy]
    Found existing installation: idna 3.12━━━━━━━━━━━━━━━━━━━━  4/14 [numpy]
    Uninstalling idna-3.12:0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/14 [numpy]
      Successfully uninstalled idna-3.12━━━━━━━━━━━━━━━━━━━━━━  4/14 [numpy]
  Attempting uninstall: h11[90m╺━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
    Found existing installation: h11 0.16.0━━━━━━━━━━━━━━━━━━━  5/14 [idna]
    Uninstalling h11-0.16.0:━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
      Successfully uninstalled h11-0.16.0━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
  Attempting uninstall: certifim━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
    Found existing installation: certifi 2026.2.25━━━━━━━━━━━━  5/14 [idna]
    Uninstalling certifi-2026.2.25:0m━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
      Successfully uninstalled certifi-2026.2.25━━━━━━━━━━━━━━  5/14 [idna]
  Attempting uninstall: python-dateutil━━━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
    Found existing installation: python-dateutil 2.9.0.post0━━  5/14 [idna]
    Uninstalling python-dateutil-2.9.0.post0:━━━━━━━━━━━━━━━━━  5/14 [idna]
      Successfully uninstalled python-dateutil-2.9.0.post0━━━━  5/14 [idna]
  Attempting uninstall: httpcore━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
    Found existing installation: httpcore 1.0.9━━━━━━━━━━━━━━━  5/14 [idna]
    Uninstalling httpcore-1.0.9:━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
      Successfully uninstalled httpcore-1.0.9━━━━━━━━━━━━━━━━━  5/14 [idna]
  Attempting uninstall: anyio[0m━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
    Found existing installation: anyio 4.13.0━━━━━━━━━━━━━━━━━  5/14 [idna]
    Uninstalling anyio-4.13.0:0m━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [idna]
      Successfully uninstalled anyio-4.13.0━━━━━━━━━━━━━━━━━━━  5/14 [idna]
  Attempting uninstall: pandas━━━━━━╸━━━━━━━━━━━ 10/14 [anyio]
    Found existing installation: pandas 2.3.3m━━━━━━━━━━━ 10/14 [anyio]
    Uninstalling pandas-2.3.3:━━╸━━━━━━━━━━━ 10/14 [anyio]
      Successfully uninstalled pandas-2.3.3[0m━━━━━━━━━━━ 10/14 [anyio]
  Attempting uninstall: httpx━━━━━━━━━━╺━━━━━━━━ 11/14 [pandas]
    Found existing installation: httpx 0.28.1━━━━━━━━ 11/14 [pandas]
    Uninstalling httpx-0.28.1:━━━━━╺━━━━━━━━ 11/14 [pandas]
      Successfully uninstalled httpx-0.28.1m╺━━━━━━━━ 11/14 [pandas]
  Attempting uninstall: picsure━━━━╺━━━━━━━━ 11/14 [pandas]
    Found existing installation: picsure 0.1.0[0m━━━━━━━━ 11/14 [pandas]
    Uninstalling picsure-0.1.0:━━━━╺━━━━━━━━ 11/14 [pandas]
      Successfully uninstalled picsure-0.1.0╺━━━━━━━━ 11/14 [pandas]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/14 [picsure] [pandas]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.14.1 requires numpy<2.3,>=1.23.5, but you have numpy 2.4.4 which is incompatible.
Successfully installed anyio-4.13.0 certifi-2026.2.25 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 idna-3.12 numpy-2.4.4 pandas-2.3.3 picsure-0.1.0 python-dateutil-2.9.0.post0 pytz-2026.1.post1 six-1.17.0 typing_extensions-4.15.0 tzdata-2026.1

In [2]:
import picsure

In [3]:
token_file = "token.txt"

with open(token_file, "r") as f:
    my_token = f.read()

In [4]:
authorized_session = picsure.connect(
    picsure.Platform.BDC_PREDEV_AUTHORIZED,
    my_token,
    dev_mode=True
)

picsure.http /psama/user/me 200 282ms in=0B out=24.6KB retry=0
picsure.http /picsure/info/resources 200 141ms in=0B out=264B retry=0
picsure.http /psama/user/me/queryTemplate/ 200 133ms in=0B out=11.0KB retry=0
picsure.http /picsure/proxy/dictionary-api/concepts?page_number=0&page_size=1 200 163ms in=6.3KB out=635B retry=0
picsure.connect connect 0ms

You're successfully connected to BDC Authorized as user george_colon@hms.harvard.edu!
Your token expires on unknown.

In [5]:
all_facets = authorized_session.showAllFacets()
all_facets

picsure.http /picsure/proxy/dictionary-api/facets 200 142ms in=6.3KB out=110.8KB retry=0
picsure.fn session.showAllFacets 144ms

,category,Category Display,display,description,value,count
0,dataset_id,Dataset,RECOVER_Adult (phs003463),Researching COVID to Enhance Recovery (RECOVER...,phs003463,160676
1,dataset_id,Dataset,FHS (phs000007),Framingham Cohort,phs000007,54984
2,dataset_id,Dataset,BioLINCC_FHS (phs003594),Framingham Heart Study (FHS) BioLINCC,phs003594,34808
3,dataset_id,Dataset,ARIC (phs000280),Atherosclerosis Risk in Communities (ARIC) Cohort,phs000280,26106
4,dataset_id,Dataset,RECOVER_Pediatric (phs003461),Researching COVID to Enhance Recovery (RECOVER...,phs003461,20680
...,...,...,...,...,...,...
480,data_source,Data Type,Genomic,Associated with genomic data,data_source_genomic,259
481,data_source,Data Type,Biosamples,Associated with biosample data,data_source_biosamples,145
482,data_source,Data Type,Electrocardiogram,Associated with electrocardiogram data,data_source_electrocardiogram,0
483,data_type,Type of Variable,Categorical,,categorical,282035
484,data_type,Type of Variable,Continuous,,continuous,205326

In [6]:
#all_facets[all_facets['value'].str.contains('biolincc')]
#all_facets[all_facets['value'] == 'tutorial-biolincc_framingham']
tutorial_biolincc_framingham_facet = authorized_session.facets()
tutorial_biolincc_framingham_facet.add('dataset_id', 'tutorial-biolincc_framingham')

picsure.http /picsure/proxy/dictionary-api/facets 200 152ms in=6.3KB out=110.8KB retry=0
picsure.fn session.facets 154ms

In [7]:
#tutorial_search_results = authorized_session.search("Current cigarette smoking at exam", facets=tutorial_biolincc_framingham_facet)
tutorial_search_results = authorized_session.search("Current cigarette smoking at exam")
#tutorial_search_results = authorized_session.search("smoke", facets=tutorial_biolincc_framingham_facet)
tutorial_search_results

picsure.http /picsure/proxy/dictionary-api/concepts?page_number=0&page_size=487375 200 159ms in=6.4KB out=6.7KB retry=0
picsure.fn session.search 160ms

,conceptPath,name,display,description,dataType,studyId,values,min,max,allowFiltering,meta,studyAcronym
0,\tutorial-biolincc_framingham\CURSMOKE\,CURSMOKE,CURSMOKE,Current cigarette smoking at exam,Categorical,tutorial-biolincc_framingham,"[Current smoker, Not current smoker]",None,None,True,None,biolincc_framingham
1,\phs000007\pht012916\phv00525306\STATUS9\,phv00525306,STATUS9,"Cigarette Smoking Status, Exam 9",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
2,\phs000007\pht012916\phv00525305\STATUS8\,phv00525305,STATUS8,"Cigarette Smoking Status, Exam 8",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
3,\phs000007\pht012916\phv00525302\STATUS5\,phv00525302,STATUS5,"Cigarette Smoking Status, Exam 5",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
4,\phs000007\pht012916\phv00566385\STATUS10\,phv00566385,STATUS10,"Cigarette Smoking Status, Exam 10",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
5,\phs000007\pht012916\phv00525301\STATUS4\,phv00525301,STATUS4,"Cigarette Smoking Status, Exam 4",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
6,\phs000007\pht012916\phv00525304\STATUS7\,phv00525304,STATUS7,"Cigarette Smoking Status, Exam 7",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
7,\phs000007\pht012916\phv00525303\STATUS6\,phv00525303,STATUS6,"Cigarette Smoking Status, Exam 6",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
8,\phs000007\pht012916\phv00525298\STATUS1\,phv00525298,STATUS1,"Cigarette Smoking Status, Exam 1",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
9,\phs000007\pht012916\phv00525300\STATUS3\,phv00525300,STATUS3,"Cigarette Smoking Status, Exam 3",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
10,\phs000007\pht012916\phv00525299\STATUS2\,phv00525299,STATUS2,"Cigarette Smoking Status, Exam 2",Categorical,phs000007,"[Current smoker, Former smoker, Never smoker]",None,None,True,None,FHS
11,\phs000209\pht001120\phv00087017\cig4c\,phv00087017,cig4c,"CIGARETTE SMOKING STATUS, EXAM 4",Categorical,phs000209,"[CURRENT, FORMER, NEVER]",None,None,True,None,MESA
12,\phs000209\pht003086\phv00175450\cig5c\,phv00175450,cig5c,"CIGARETTE SMOKING STATUS, EXAM 5",Categorical,phs000209,"[CURRENT, FORMER, NEVER]",None,None,True,None,MESA
13,\phs000209\pht003091\phv00176884\cig5c\,phv00176884,cig5c,"CIGARETTE SMOKING STATUS, EXAM 5",Categorical,phs000209,"[CURRENT, FORMER, NEVER]",None,None,True,None,MESA
14,\phs000209\pht001112\phv00083613\cig1ca4\,phv00083613,cig1ca4,CIGARETTE SMOKING STATUS,Categorical,phs000209,"[CURRENT, FORMER, NEVER]",None,None,True,None,MESA
15,\phs000209\pht001122\phv00087839\cig1ca4\,phv00087839,cig1ca4,CIGARETTE SMOKING STATUS,Categorical,phs000209,"[CURRENT, FORMER, NEVER]",None,None,True,None,MESA
16,\phs000209\pht001114\phv00083843\cig1ca4\,phv00083843,cig1ca4,CIGARETTE SMOKING STATUS,Categorical,phs000209,"[CURRENT, FORMER, NEVER]",None,None,True,None,MESA
17,\phs000209\pht001111\phv00083241\cig1c\,phv00083241,cig1c,CIGARETTE SMOKING STATUS,Categorical,phs000209,"[CURRENT, FORMER, NEVER]",None,None,True,None,MESA
18,\phs000209\pht001121\phv00087082\cigfc\,phv00087082,cigfc,CIGARETTE SMOKING STATUS,Categorical,phs000209,"[CURRENT, FORMER, NEVER]",None,None,True,None,MESA

In [8]:
tutorial_search_results['values']

0              [Current smoker, Not current smoker]
1     [Current smoker, Former smoker, Never smoker]
2     [Current smoker, Former smoker, Never smoker]
3     [Current smoker, Former smoker, Never smoker]
4     [Current smoker, Former smoker, Never smoker]
5     [Current smoker, Former smoker, Never smoker]
6     [Current smoker, Former smoker, Never smoker]
7     [Current smoker, Former smoker, Never smoker]
8     [Current smoker, Former smoker, Never smoker]
9     [Current smoker, Former smoker, Never smoker]
10    [Current smoker, Former smoker, Never smoker]
11                         [CURRENT, FORMER, NEVER]
12                         [CURRENT, FORMER, NEVER]
13                         [CURRENT, FORMER, NEVER]
14                         [CURRENT, FORMER, NEVER]
15                         [CURRENT, FORMER, NEVER]
16                         [CURRENT, FORMER, NEVER]
17                         [CURRENT, FORMER, NEVER]
18                         [CURRENT, FORMER, NEVER]
Name: values, dtype: object

In [9]:
cursmoke_var = tutorial_search_results[tutorial_search_results['name'] == 'CURSMOKE']
cursmoke_var

,conceptPath,name,display,description,dataType,studyId,values,min,max,allowFiltering,meta,studyAcronym
0,\tutorial-biolincc_framingham\CURSMOKE\,CURSMOKE,CURSMOKE,Current cigarette smoking at exam,Categorical,tutorial-biolincc_framingham,"[Current smoker, Not current smoker]",None,None,True,None,biolincc_framingham

In [41]:
raw_values = cursmoke_var['values'].iloc[0]
raw_values

['Current smoker', 'Not current smoker']

In [39]:
cursmoke = picsure.createClause(
    cursmoke_var['conceptPath'],
    type=picsure.ClauseType.FILTER,
    categories=cursmoke_var['values'].iloc[0]
)

In [40]:
query = authorized_session.runQuery(cursmoke)

picsure.http /picsure/v3/query/sync 200 10143ms in=326B out=4B retry=0
picsure.fn session.runQuery 10143ms

In [42]:
query.value

4434

In [43]:
authorized_session.dev_events()

,timestamp,kind,name,duration_ms,bytes_in,bytes_out,status,retry,error,metadata
0,2026-04-21 22:08:40.765045+00:00,http,/psama/user/me,282.375333,0.0,25233.0,200.0,0,None,{}
1,2026-04-21 22:08:40.906650+00:00,http,/picsure/info/resources,141.141875,0.0,264.0,200.0,0,None,{}
2,2026-04-21 22:08:41.040450+00:00,http,/psama/user/me/queryTemplate/,132.846625,0.0,11263.0,200.0,0,None,{}
3,2026-04-21 22:08:41.204898+00:00,http,/picsure/proxy/dictionary-api/concepts?page_nu...,162.677291,6495.0,635.0,200.0,0,None,{}
4,2026-04-21 22:08:41.207662+00:00,connect,connect,0.000000,NaN,NaN,NaN,0,None,"{'resources': 5, 'consents': 427, 'total_conce..."
5,2026-04-21 22:08:41.372570+00:00,http,/picsure/proxy/dictionary-api/facets,141.689084,6495.0,113474.0,200.0,0,None,{}
6,2026-04-21 22:08:41.375038+00:00,function,session.showAllFacets,144.219958,NaN,NaN,NaN,0,None,"{'df_rows': 485, 'df_cols': 6}"
7,2026-04-21 22:08:41.586372+00:00,http,/picsure/proxy/dictionary-api/facets,152.032041,6495.0,113474.0,200.0,0,None,{}
8,2026-04-21 22:08:41.587964+00:00,function,session.facets,153.694417,NaN,NaN,NaN,0,None,{}
9,2026-04-21 22:08:42.032994+00:00,http,/picsure/proxy/dictionary-api/concepts?page_nu...,159.191291,6528.0,6854.0,200.0,0,None,{}
10,2026-04-21 22:08:42.033782+00:00,function,session.search,160.040000,NaN,NaN,NaN,0,None,"{'df_rows': 19, 'df_cols': 12}"
11,2026-04-21 22:08:42.695495+00:00,http,/picsure/v3/query/sync,130.031208,328.0,98.0,500.0,0,None,{}
12,2026-04-21 22:08:42.695832+00:00,error,/picsure/v3/query/sync,130.391291,NaN,NaN,NaN,0,TransportServerError,{'method': 'POST'}
13,2026-04-21 22:08:42.696125+00:00,error,session.runQuery,131.273417,NaN,NaN,NaN,0,PicSureConnectionError,{}
14,2026-04-21 22:09:52.770710+00:00,http,/picsure/v3/query/sync,326.946458,328.0,98.0,500.0,0,None,{}
15,2026-04-21 22:09:52.771506+00:00,error,/picsure/v3/query/sync,327.860083,NaN,NaN,NaN,0,TransportServerError,{'method': 'POST'}
16,2026-04-21 22:09:52.771889+00:00,error,session.runQuery,328.301167,NaN,NaN,NaN,0,PicSureConnectionError,{}
17,2026-04-21 22:11:21.798509+00:00,http,/picsure/v3/query/sync,340.519750,328.0,98.0,500.0,0,None,{}
18,2026-04-21 22:11:21.799114+00:00,error,/picsure/v3/query/sync,341.162542,NaN,NaN,NaN,0,TransportServerError,{'method': 'POST'}
19,2026-04-21 22:11:21.799542+00:00,error,session.runQuery,341.622625,NaN,NaN,NaN,0,PicSureConnectionError,{}
20,2026-04-21 22:15:52.204829+00:00,error,session.runQuery,0.689959,NaN,NaN,NaN,0,TypeError,{}
21,2026-04-21 22:16:17.936339+00:00,http,/picsure/v3/query/sync,358.451000,328.0,98.0,500.0,0,None,{}
22,2026-04-21 22:16:17.936740+00:00,error,/picsure/v3/query/sync,358.876875,NaN,NaN,NaN,0,TransportServerError,{'method': 'POST'}
23,2026-04-21 22:16:17.937060+00:00,error,session.runQuery,359.219625,NaN,NaN,NaN,0,PicSureConnectionError,{}
24,2026-04-21 22:18:49.056740+00:00,http,/picsure/v3/query/sync,282.275250,328.0,98.0,500.0,0,None,{}
25,2026-04-21 22:18:49.059524+00:00,error,/picsure/v3/query/sync,285.157834,NaN,NaN,NaN,0,TransportServerError,{'method': 'POST'}
26,2026-04-21 22:18:49.060380+00:00,error,session.runQuery,286.059709,NaN,NaN,NaN,0,PicSureConnectionError,{}
27,2026-04-21 22:23:42.607434+00:00,http,/picsure/v3/query/sync,10142.589417,326.0,4.0,200.0,0,None,{}
28,2026-04-21 22:23:42.607875+00:00,function,session.runQuery,10143.111416,NaN,NaN,NaN,0,None,{}